-----------------------------------------------------------------------------
-- |
-- Module      :  UseCaseModel.PrettyPrinter.Latex
-- Copyright   :  (c) Rodrigo Bonifacio 2008, 2009
-- License     :  LGPL
--
-- Maintainer  :  rba2@cin.ufpe.br
-- Stability   :  provisional
-- Portability :  portable
--
-- A Latex pretty printer for our Use Case Model data type. Useful for 
-- generating ps or pdf files from a use case model.
--
--
-----------------------------------------------------------------------------

module UseCaseModel.PrettyPrinter.Latex (ucmToLatex)
where 

import Text.PrettyPrint.HughesPJ

import UseCaseModel.Types
 
ucmToLatex :: UseCaseModel -> Doc
ucmToLatex (UCM name ucs as) = vcat [ beginDocument name 
                                    , endDocument
                                    ]


beginDocument :: String -> Doc
beginDocument name =
 vcat [ text "%This Latex file is machine-generated by the Hephaestus\n"
      , text "documentclass[a4paper,11pt]{article}" 
      , text  "author{Hephaestus Tool Suite}" 
      , text ("title{Use Case Model for" ++ name ++ "}")
      , text "begin{document}" 
      , text "maketitle"
      ]

endDocument :: Doc
endDocument =  text "end{document}"