/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.game2d.wolf;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bkg01=0x7f020000;
        public static final int bkg02=0x7f020001;
        public static final int bkg03=0x7f020002;
        public static final int gunthugextended=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int thugs=0x7f020005;
        public static final int tiles01=0x7f020006;
        public static final int tiles02=0x7f020007;
        public static final int wolverine=0x7f020008;
        public static final int wolves=0x7f020009;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
